"""drop_preferences_table

Revision ID: 3fca5c006215
Revises: 78f5ff1bdc3f
Create Date: 2026-07-28 12:37:35.843005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fca5c006215'
down_revision: Union[str, None] = '78f5ff1bdc3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_preferences_user_id', table_name='preferences')
    op.drop_table('preferences')
    op.add_column('saved_searches', sa.Column('mode', sa.String(length=20), nullable=False, comment='Search mode used for this saved search (NORMAL or SMART)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_searches', 'mode')
    op.create_table('preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Unique identifier for preference record'),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID of owning user account'),
    sa.Column('preferred_roles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment="List of target job titles (e.g. ['Backend Engineer', 'Python Developer'])"),
    sa.Column('preferred_locations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment="List of target geographic locations (e.g. ['San Francisco, CA', 'Remote'])"),
    sa.Column('min_salary', sa.INTEGER(), autoincrement=False, nullable=True, comment='Minimum acceptable annual salary in USD'),
    sa.Column('max_salary', sa.INTEGER(), autoincrement=False, nullable=True, comment='Target maximum annual salary in USD'),
    sa.Column('work_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment="Work location arrangement: 'remote', 'hybrid', or 'onsite'"),
    sa.Column('preferred_companies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment="List of target dream companies (e.g. ['Stripe', 'Notion', 'Figma'])"),
    sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=False, comment='Years of professional experience'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Timestamp when preferences were last modified'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='preferences_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='preferences_pkey')
    )
    op.create_index('ix_preferences_user_id', 'preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###
