"""initial_schema_with_users

Revision ID: 4a8657b9e7ac
Revises: 
Create Date: 2026-07-23 09:51:08.070569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8657b9e7ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the job'),
    sa.Column('company', sa.String(length=255), nullable=False, comment='Company name offering the position'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Job title or role name'),
    sa.Column('location', sa.String(length=255), nullable=False, comment="Location string (e.g., 'San Francisco, CA' or 'Remote')"),
    sa.Column('remote', sa.Boolean(), nullable=False, comment='True if the position allows remote work'),
    sa.Column('salary', sa.String(length=100), nullable=True, comment="Salary range or note (e.g., '$120,000 - $150,000' or None if unlisted)"),
    sa.Column('description', sa.Text(), nullable=False, comment='Full job description text'),
    sa.Column('url', sa.String(length=1024), nullable=False, comment='Direct application or job listing URL'),
    sa.Column('source', sa.String(length=50), nullable=False, comment="Source provider name (e.g., 'greenhouse', 'lever', 'ashby')"),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA256 hash of company+title+location used for duplicate detection'),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=False, comment='When the job was originally posted or fetched'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='When Finder discovered this job listing'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index(op.f('ix_jobs_content_hash'), 'jobs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_jobs_source'), 'jobs', ['source'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_index(op.f('ix_jobs_url'), 'jobs', ['url'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique user account identifier'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address used for login'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='User full name'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Argon2 hashed password string'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether user account is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when user registered'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when user last logged in'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the application'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID of owning user candidate'),
    sa.Column('job_id', sa.UUID(), nullable=False, comment='ID of the associated job posting'),
    sa.Column('status', sa.String(length=50), nullable=False, comment="Application status code (e.g. 'saved', 'approved', 'completed', 'interview')"),
    sa.Column('match_score', sa.Float(), nullable=True, comment='Match score percentage snapshot when application was created'),
    sa.Column('match_details', sa.JSON(), nullable=True, comment='Snapshot of AI match explanation payload'),
    sa.Column('notes', sa.Text(), nullable=True, comment='User notes (e.g. interview preparation, referral details)'),
    sa.Column('applied_date', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when application submission was confirmed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job_application')
    )
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('preferences',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for preference record'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID of owning user account'),
    sa.Column('preferred_roles', sa.JSON(), nullable=False, comment="List of target job titles (e.g. ['Backend Engineer', 'Python Developer'])"),
    sa.Column('preferred_locations', sa.JSON(), nullable=False, comment="List of target geographic locations (e.g. ['San Francisco, CA', 'Remote'])"),
    sa.Column('min_salary', sa.Integer(), nullable=True, comment='Minimum acceptable annual salary in USD'),
    sa.Column('max_salary', sa.Integer(), nullable=True, comment='Target maximum annual salary in USD'),
    sa.Column('work_type', sa.String(length=50), nullable=False, comment="Work location arrangement: 'remote', 'hybrid', or 'onsite'"),
    sa.Column('preferred_companies', sa.JSON(), nullable=False, comment="List of target dream companies (e.g. ['Stripe', 'Notion', 'Figma'])"),
    sa.Column('experience_years', sa.Integer(), nullable=False, comment='Years of professional experience'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when preferences were last modified'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferences_user_id'), 'preferences', ['user_id'], unique=True)
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the resume'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID of owning user account'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment="Original uploaded filename (e.g. 'John_Doe_Resume.pdf')"),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='Path on disk where PDF is saved'),
    sa.Column('raw_text', sa.Text(), nullable=True, comment='Extracted raw plain text from PDF file'),
    sa.Column('parsed_data', sa.JSON(), nullable=True, comment='Structured JSON extracted by AI (skills, experience, education, projects)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True if this is the active resume used for job matching'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when resume was uploaded'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('application_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique log entry identifier'),
    sa.Column('application_id', sa.UUID(), nullable=False, comment='ID of parent application'),
    sa.Column('action', sa.String(length=100), nullable=False, comment="Action summary (e.g. 'Status Changed', 'Automation Started')"),
    sa.Column('old_status', sa.String(length=50), nullable=True, comment='Previous status string before transition'),
    sa.Column('new_status', sa.String(length=50), nullable=False, comment='New status string after transition'),
    sa.Column('details', sa.Text(), nullable=True, comment='Detailed explanation or log output'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when audit log entry was created'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_logs_application_id'), 'application_logs', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_logs_application_id'), table_name='application_logs')
    op.drop_table('application_logs')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_preferences_user_id'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_jobs_url'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_content_hash'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
