"""Add last_verified_date to jobs

Revision ID: 78f5ff1bdc3f
Revises: 4a8657b9e7ac
Create Date: 2026-07-23 17:26:16.189402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f5ff1bdc3f'
down_revision: Union[str, None] = '4a8657b9e7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('last_verified_date', sa.DateTime(timezone=True), nullable=True, comment='When this job was last verified as active'))
    op.execute("UPDATE jobs SET last_verified_date = fetched_at WHERE last_verified_date IS NULL")
    op.alter_column('jobs', 'last_verified_date', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'last_verified_date')
    # ### end Alembic commands ###
