"""Add apply_url and can_apply to jobs

Revision ID: b529badbe324
Revises: b7d2c94f1357
Create Date: 2026-07-29 12:30:08.016571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b529badbe324'
down_revision: Union[str, None] = 'b7d2c94f1357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('apply_url', sa.String(length=1024), nullable=True, comment='Direct application form link'))
    op.add_column('jobs', sa.Column('can_apply', sa.Boolean(), server_default='false', nullable=False, comment='True if the job has an external application URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'can_apply')
    op.drop_column('jobs', 'apply_url')
    # ### end Alembic commands ###
